  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: reservation-service-deployment


  spec:
    replicas: 2
    selector:
      matchLabels:
        app: reservation-service
    template:
      metadata:
        labels:
          app: reservation-service
      spec:
        containers:
          - name: reservation-service
            image: quarkus/reservation-service-jvm:latest
            imagePullPolicy: Never
            ports:
              - containerPort: 8080

  
